window.MOON_ROAM_DATA = {
  "version": 2,
  "radius": 1737400,
  "start": "change6",
  "scope": "1966—2025 · 月面探测历史任务选集，包含蓝色幽灵1号；非截至今日的全部任务清单。配图复用对应图鉴，参考图与历史照片的区别见各图说明。",
  "articles": {
    "history": {
      "title": "「月球探测」是什么,探测一般需要经历什么流程和阶段,有哪些著名或者典型的月球探测器吗?",
      "url": "https://www.zhihu.com/question/314672426/answer/616073103",
      "author": "ZEGBUL",
      "votes": 308,
      "summary": "回顾从早期无人探测到软着陆、巡视与采样返回的技术路线，适合对照月球号和勘测者系列阅读。",
      "retrieved": "2026-09-19",
      "kind": "知乎相关讨论",
      "thumbnail": "assets/roam/apollo.svg",
      "thumbnailLabel": "主题示意图 · 非原文配图"
    },
    "apollo": {
      "title": "天文史上的今天 | 阿波罗登月留下的痕迹",
      "url": "https://zhuanlan.zhihu.com/p/39698191",
      "author": "shn117",
      "votes": 37,
      "summary": "从轨道器拍到的登月舱、科学仪器和足迹，回看阿波罗 12 与勘测者 3 的月面相遇。",
      "retrieved": "2026-09-19",
      "kind": "知乎相关讨论",
      "thumbnail": "assets/roam/apollo.svg",
      "thumbnailLabel": "主题示意图 · 非原文配图"
    },
    "change": {
      "title": "科学私房课第九十七讲 中国探月工程 嫦娥五号",
      "url": "https://zhuanlan.zhihu.com/p/335759143",
      "author": "张斌",
      "votes": 53,
      "summary": "通过“绕、落、回”的任务分工，解释嫦娥系列如何从遥感走向巡视和采样返回。",
      "retrieved": "2026-09-19",
      "kind": "知乎相关讨论",
      "thumbnail": "assets/roam/change.svg",
      "thumbnailLabel": "主题示意图 · 非原文配图"
    },
    "change6": {
      "title": "目前,关于嫦娥六号带回月壤的相关研究已经揭示了哪些问题?",
      "url": "https://www.zhihu.com/question/7709467856/answer/63420312258",
      "author": "杨溢",
      "votes": 440,
      "summary": "围绕嫦娥六号返回的月背样品，讨论已有研究如何帮助理解月球两面的地质差异。",
      "retrieved": "2026-09-19",
      "kind": "知乎相关讨论",
      "thumbnail": "assets/roam/change6.svg",
      "thumbnailLabel": "主题示意图 · 非原文配图"
    },
    "chandra": {
      "title": "印度「月船 3 号」探测器成功登月,成为第一个在月球南极着陆的国家,这对人类登月有哪些意义?",
      "url": "https://www.zhihu.com/question/618698213/answer/3179388607",
      "author": "太空僧",
      "votes": 3040,
      "summary": "回顾月船三号成功软着陆的背景，并说明其南纬约 69°的落点与地理南极的区别。",
      "retrieved": "2026-09-19",
      "kind": "知乎相关讨论",
      "thumbnail": "assets/roam/chandra.svg",
      "thumbnailLabel": "主题示意图 · 非原文配图"
    },
    "poles": {
      "title": "中国航天宣布月球科研站,为何选择南极?",
      "url": "https://www.zhihu.com/question/653146710/answer/3483214515",
      "author": "张英锋",
      "votes": 484,
      "summary": "从供能、水冰和科学观测角度讨论月球南极选址。永久阴影只存在于特定地形中，并不等于整个月背。",
      "retrieved": "2026-09-19",
      "kind": "知乎相关讨论",
      "thumbnail": "assets/roam/poles.svg",
      "thumbnailLabel": "主题示意图 · 非原文配图"
    },
    "basin": {
      "title": "嫦娥六号成功着陆在月球背面南极-艾特肯盆地,即将开始月背采样,有哪些突破?后续任务还面临哪些挑战?",
      "url": "https://www.zhihu.com/question/657884799/answer/3517613546",
      "author": "杨溢",
      "votes": 232,
      "summary": "解释嫦娥六号为何选择南极—艾特肯盆地内的阿波罗盆地，以及月背采样的科学动机。文章写于采样返回完成之前。",
      "retrieved": "2026-09-19",
      "kind": "知乎相关讨论",
      "thumbnail": "assets/roam/poles.svg",
      "thumbnailLabel": "主题示意图 · 非原文配图"
    },
    "blueghost": {
      "title": "美国萤火虫公司「蓝色幽灵号」月球着陆器成功着陆月球,成为首家成功登月的商业公司,有哪些意义?",
      "url": "https://www.zhihu.com/question/13843765292/answer/114555223694",
      "author": "吕坚豪",
      "votes": 491,
      "summary": "萤火虫航天（Firefly Aerospace）的蓝色幽灵一号于 2025 年 3 月 2 日在月球正面危海稳定直立着陆，携带 10 台 NASA 科学与技术仪器，开展月尘、月壤、导航等研究。任务于同年 3 月结束。知乎回答讨论这次商业月球探测的意义和仪器用途；其中其他任务的后续发射、着陆安排是发表当时的预期。",
      "retrieved": "2026-09-19",
      "kind": "知乎相关讨论",
      "thumbnail": "./assets/rover-codex/blueghost-reference.png",
      "thumbnailLabel": "用户提供的风格参考图 · 非历史照片"
    }
  },
  "sites": [
    {
      "id": "luna9",
      "name": "月球 9 号",
      "country": "苏联",
      "date": "1966-02-03",
      "lat": 7.08,
      "lon": -64.37,
      "region": "风暴洋",
      "model": "petal",
      "read": "history",
      "summary": "首次成功月面软着陆，传回月面全景图像。落点为历史估计位置，尚不作为精确遗址定位。",
      "official": "https://nssdc.gsfc.nasa.gov/planetary/lunar/lunarussr.html",
      "kind": "mission",
      "codexId": "luna9-lander"
    },
    {
      "id": "surveyor1",
      "name": "勘测者 1 号",
      "country": "美国",
      "date": "1966-06-02",
      "lat": -2.4745,
      "lon": -43.3398,
      "region": "风暴洋",
      "model": "surveyor",
      "read": "history",
      "summary": "美国首次月面软着陆，验证月壤承载条件并拍摄月面。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "surveyor1-lander"
    },
    {
      "id": "luna13",
      "name": "月球 13 号",
      "country": "苏联",
      "date": "1966-12-24",
      "lat": 18.8667,
      "lon": -62.05,
      "region": "风暴洋",
      "model": "petal",
      "read": "history",
      "summary": "在月面进行土壤物理性质测量。落点使用历史近似坐标。",
      "official": "https://nssdc.gsfc.nasa.gov/planetary/lunar/lunarussr.html",
      "kind": "mission",
      "codexId": "luna13-lander"
    },
    {
      "id": "surveyor3",
      "name": "勘测者 3 号",
      "country": "美国",
      "date": "1967-04-20",
      "lat": -3.0162,
      "lon": -23.418,
      "region": "风暴洋",
      "model": "surveyor",
      "read": "apollo",
      "summary": "机械臂探测月壤；阿波罗 12 宇航员后来到访并带回部分部件。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "surveyor3-lander"
    },
    {
      "id": "surveyor5",
      "name": "勘测者 5 号",
      "country": "美国",
      "date": "1967-09-11",
      "lat": 1.4551,
      "lon": 23.1943,
      "region": "静海",
      "model": "surveyor",
      "read": "history",
      "summary": "对月壤进行原位元素分析，帮助了解月海物质。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "surveyor5-lander"
    },
    {
      "id": "surveyor6",
      "name": "勘测者 6 号",
      "country": "美国",
      "date": "1967-11-10",
      "lat": 0.4742,
      "lon": -1.4275,
      "region": "中央湾",
      "model": "surveyor",
      "read": "history",
      "summary": "完成月面成像与成分测量，并进行短距离发动机跳跃试验。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "surveyor6-lander"
    },
    {
      "id": "surveyor7",
      "name": "勘测者 7 号",
      "country": "美国",
      "date": "1968-01-10",
      "lat": -40.9812,
      "lon": -11.5127,
      "region": "第谷坑北侧高地",
      "model": "surveyor",
      "read": "history",
      "summary": "勘测者系列最后一次着陆，探索不同于月海的南部高地。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "surveyor7-lander"
    },
    {
      "id": "apollo11",
      "name": "阿波罗 11",
      "country": "美国",
      "date": "1969-07-20",
      "lat": 0.67416,
      "lon": 23.47314,
      "region": "静海基地",
      "model": "apollo",
      "read": "apollo",
      "summary": "阿姆斯特朗与奥尔德林完成首次载人登月，采集月岩并部署实验。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "apollo11-lander"
    },
    {
      "id": "apollo12",
      "name": "阿波罗 12",
      "country": "美国",
      "date": "1969-11-19",
      "lat": -3.0128,
      "lon": -23.4219,
      "region": "风暴洋",
      "model": "apollo",
      "read": "apollo",
      "summary": "实现接近预定目标的着陆；步行访问勘测者 3，连接两代探月任务。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "apollo12-lander"
    },
    {
      "id": "luna16",
      "name": "月球 16 号",
      "country": "苏联",
      "date": "1970-09-20",
      "lat": -0.5137,
      "lon": 56.3638,
      "region": "丰富海",
      "model": "sample",
      "read": "history",
      "summary": "首次无人月球采样返回任务，将钻取的月壤送回地球。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "luna16-lander"
    },
    {
      "id": "luna17",
      "name": "月球 17 号",
      "country": "苏联",
      "date": "1970-11-17",
      "lat": 38.23764,
      "lon": -35.00163,
      "region": "雨海",
      "model": "lunokhod",
      "read": "history",
      "summary": "运送月球车 1 号，开启遥控月面长距离巡视。这里标注的是着陆器位置。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "luna17-lander"
    },
    {
      "id": "apollo14",
      "name": "阿波罗 14",
      "country": "美国",
      "date": "1971-02-05",
      "lat": -3.64589,
      "lon": -17.47194,
      "region": "弗拉·毛罗高地",
      "model": "apollo",
      "read": "apollo",
      "summary": "探索与雨海撞击事件有关的高地物质，部署科学仪器。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "apollo14-lander"
    },
    {
      "id": "apollo15",
      "name": "阿波罗 15",
      "country": "美国",
      "date": "1971-07-30",
      "lat": 26.13239,
      "lon": 3.6333,
      "region": "哈德利—亚平宁",
      "model": "apollo",
      "read": "apollo",
      "summary": "首次使用载人月球车，沿哈德利月溪和山麓扩大采样范围。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "falcon-lander"
    },
    {
      "id": "luna20",
      "name": "月球 20 号",
      "country": "苏联",
      "date": "1972-02-21",
      "lat": 3.7863,
      "lon": 56.6242,
      "region": "丰富海附近高地",
      "model": "sample",
      "read": "history",
      "summary": "无人采样返回月球高地样品，与月海样品形成对照。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "luna20-lander"
    },
    {
      "id": "apollo16",
      "name": "阿波罗 16",
      "country": "美国",
      "date": "1972-04-21",
      "lat": -8.9734,
      "lon": 15.5011,
      "region": "笛卡尔高地",
      "model": "apollo",
      "read": "apollo",
      "summary": "驾驶月球车考察高地，采样研究撞击对月壳的改造。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "orion-lander"
    },
    {
      "id": "apollo17",
      "name": "阿波罗 17",
      "country": "美国",
      "date": "1972-12-11",
      "lat": 20.1911,
      "lon": 30.7723,
      "region": "陶拉斯—利特罗",
      "model": "apollo",
      "read": "apollo",
      "summary": "阿波罗计划最后一次载人登月，地质学家施密特参与并发现橙色土。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "challenger-lander"
    },
    {
      "id": "luna21",
      "name": "月球 21 号",
      "country": "苏联",
      "date": "1973-01-15",
      "lat": 25.9994,
      "lon": 30.4076,
      "region": "勒莫尼耶坑",
      "model": "lunokhod",
      "read": "history",
      "summary": "运送月球车 2 号，进行地形、磁场与月面巡视研究。这里标注的是着陆器位置。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "luna21-lander"
    },
    {
      "id": "luna24",
      "name": "月球 24 号",
      "country": "苏联",
      "date": "1976-08-18",
      "lat": 12.7142,
      "lon": 62.2129,
      "region": "危海",
      "model": "sample",
      "read": "history",
      "summary": "钻取较深的月壤柱并返回地球，是苏联最后一次月球采样返回。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "luna24-lander"
    },
    {
      "id": "change3",
      "name": "嫦娥三号",
      "country": "中国",
      "date": "2013-12-14",
      "lat": 44.1214,
      "lon": -19.5117,
      "region": "雨海北部",
      "model": "change",
      "read": "change",
      "summary": "中国首次月面软着陆，释放玉兔号开展巡视探测。",
      "official": "https://lroc.im-ldi.com/images/938",
      "kind": "mission",
      "codexId": "change3-lander"
    },
    {
      "id": "change4",
      "name": "嫦娥四号",
      "country": "中国",
      "date": "2019-01-03",
      "lat": -45.4446,
      "lon": 177.5991,
      "region": "冯·卡门坑",
      "model": "change",
      "read": "change",
      "summary": "人类首次月背软着陆，借助鹊桥中继通信，释放玉兔二号。",
      "official": "https://vsso.nssdc.ac.cn/nssdc_en/html/task/change4.html",
      "kind": "mission",
      "codexId": "change4-lander"
    },
    {
      "id": "change5",
      "name": "嫦娥五号",
      "country": "中国",
      "date": "2020-12-01",
      "lat": 43.0576,
      "lon": -51.9161,
      "region": "风暴洋北部",
      "model": "change",
      "read": "change",
      "summary": "中国首次地外天体采样返回，研究年轻月海玄武岩。",
      "official": "https://lroc.im-ldi.com/images/1172.2020",
      "kind": "mission",
      "codexId": "change5-lander"
    },
    {
      "id": "chandra3",
      "name": "月船三号",
      "country": "印度",
      "date": "2023-08-23",
      "lat": -69.373,
      "lon": 32.319,
      "region": "南部高纬区",
      "model": "vikram",
      "read": "chandra",
      "summary": "维克拉姆着陆器与智慧号巡视器开展原位探测。落点距地理南极仍约 625 公里。",
      "official": "https://www.isro.gov.in/Chandrayaan3.html",
      "kind": "mission",
      "codexId": "chandrayaan3-lander"
    },
    {
      "id": "change6",
      "name": "嫦娥六号",
      "country": "中国",
      "date": "2024-06-02 CST",
      "lat": -41.6385,
      "lon": -153.9852,
      "region": "月背·阿波罗盆地",
      "model": "change",
      "read": "change6",
      "summary": "人类首次月背采样返回。坐标采用 LROC 2024 年影像定位，水平精度估计约 ±30 米。",
      "official": "https://lroc.im-ldi.com/images/1374",
      "kind": "mission",
      "codexId": "change6-lander"
    },
    {
      "id": "blueghost1",
      "name": "蓝色幽灵1号",
      "country": "美国",
      "date": "2025-03-02",
      "lat": 18.5623,
      "lon": 61.8103,
      "region": "危海",
      "model": "bg1",
      "read": "blueghost",
      "summary": "萤火虫航天（Firefly Aerospace）的蓝色幽灵一号于 2025 年 3 月 2 日在月球正面危海稳定直立着陆，携带 10 台 NASA 科学与技术仪器，开展月尘、月壤、导航等研究。任务于同年 3 月结束。",
      "official": "https://www.nasa.gov/news-release/touchdown-carrying-nasa-science-fireflys-blue-ghost-lands-on-moon/",
      "kind": "mission",
      "codexId": "blueghost-lander"
    },
    {
      "id": "north",
      "name": "月球北极",
      "lat": 90,
      "lon": 0,
      "region": "北极",
      "summary": "跨过北极后仍可继续沿球面前进。部分极区坑底长期得不到阳光；本场景不提供真实局部光照预报。",
      "kind": "landmark",
      "country": "自然地标",
      "date": "地理地标",
      "model": "beacon",
      "read": "poles",
      "official": "https://science.nasa.gov/moon/facts/"
    },
    {
      "id": "south",
      "name": "月球南极",
      "lat": -90,
      "lon": 0,
      "region": "南极",
      "summary": "水冰与供能条件是极区探测的重要课题。南极与南极—艾特肯盆地并不是同一个点。",
      "kind": "landmark",
      "country": "自然地标",
      "date": "地理地标",
      "model": "beacon",
      "read": "poles",
      "official": "https://science.nasa.gov/moon/facts/"
    },
    {
      "id": "spa",
      "name": "南极—艾特肯盆地",
      "lat": -53,
      "lon": -169,
      "region": "月背盆地中心示意点",
      "summary": "巨大的古老撞击盆地；嫦娥四号和六号着陆区都在盆地范围内。这里是区域中心示意点。",
      "kind": "landmark",
      "country": "自然地标",
      "date": "地理地标",
      "model": "beacon",
      "read": "basin",
      "official": "https://science.nasa.gov/moon/facts/"
    },
    {
      "id": "tycho",
      "name": "第谷撞击坑",
      "lat": -43.31,
      "lon": -11.36,
      "region": "月球南部高地",
      "summary": "醒目的辐射纹撞击坑。勘测者 7 在它的北侧高地开展探测。",
      "kind": "landmark",
      "country": "自然地标",
      "date": "地理地标",
      "model": "beacon",
      "read": "poles",
      "official": "https://science.nasa.gov/moon/facts/"
    }
  ]
};
