const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/win/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),output=path.join(root,'_tmp/luna');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(path.relative(root,f).startsWith('..')||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.html':'text/html'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});
const state=p=>p.evaluate(()=>__roamDiagnostics());
async function select(p,i,action){await p.locator('#mapBtn').click();await p.locator(`[data-region="${i}"]`).click();await p.locator(`[data-action="${action}"]`).click();await p.waitForTimeout(250);}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),report={errors:[],routes:[],mobile:[]};
try{
 const p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>report.errors.push(String(e)));p.on('response',r=>{if(r.status()>=400)report.errors.push(r.status()+' '+r.url());});await p.goto(origin+'/roam.html');await p.waitForFunction(()=>window.__roamDiagnostics?.().ready);
 let s=await state(p);assert.equal(s.codex.total,38);assert.equal(s.exhibits.length,24);assert.deepEqual(s.nationalFlags.map(f=>f.mission).sort(),[3,4,5,6]);report.initialCalls=s.calls;
 for(const [i,n] of [[9,24],[10,20],[11,16]]){await select(p,i,'jump');await p.waitForTimeout(500);s=await state(p);assert.ok(s.environment.earthRendered);assert.equal(s.exhibits[i].mission,'luna'+n);assert.equal(s.exhibits[i].ascent,true);assert.equal(s.exhibits[i].rover,null);await p.screenshot({path:path.join(output,'luna'+n+'-camp.png')});await p.keyboard.down('w');await p.waitForFunction(id=>__roamDiagnostics().codex.unlocked.includes(id),'luna'+n+'-lander',{timeout:16000});await p.keyboard.up('w');await p.waitForTimeout(350);await p.screenshot({path:path.join(output,'luna'+n+'-closeup.png')});await p.keyboard.press('e');assert.ok((await p.locator('#roverCodexTitle').innerText()).includes('Luna '+n));assert.ok(await p.locator('#roverCodexBody img').evaluate(i=>i.complete&&i.naturalWidth>0));assert.equal(await p.locator('#roverCodexBody a[href*="nasa.gov"]').count(),1);assert.equal(await p.locator('#roverCodexBody a[href*="zhihu.com"]').count(),1);await p.screenshot({path:path.join(output,'luna'+n+'-codex.png')});await p.locator('#roverCodexClose').click();}
 await p.locator('#heritageBtn').click();s=await state(p);for(const i of [9,10,11]){assert.equal(s.exhibits[i].ascent,false);assert.equal(s.exhibits[i].landerVisible,true);}assert.ok(s.nationalFlags.every(f=>f.visible));await p.screenshot({path:path.join(output,'luna16-remains.png')});await p.locator('#heritageBtn').click();
 await select(p,11,'jump');await p.reload();await p.waitForFunction(()=>window.__roamDiagnostics?.().ready);s=await state(p);assert.equal(s.region,'luna16');assert.ok([16,20,24].every(n=>s.codex.unlocked.includes('luna'+n+'-lander')));
 await p.locator('#codexBtn').click();for(const n of [24,20,16]){await p.locator('[data-filter="luna'+n+'"]').click();assert.equal(await p.locator('.rover-card').count(),1);}await p.locator('#roverCodexClose').click();
 await p.locator('#mapBtn').click();assert.equal(await p.locator('#routeChoices button').count(),24);assert.ok(!/压缩|游戏米/.test(await p.locator('#atlas').innerText()));await p.screenshot({path:path.join(output,'twelve-station-map.png')});await p.locator('#historyBtn').click();assert.equal(await p.locator('.history-card').count(),24);await p.locator('#closeHistory').click();
 await select(p,2,'jump');for(const destination of [9,10,11,10,9,2]){await select(p,destination,'guide');const start=Date.now();assert.equal((await state(p)).auto,true);await p.waitForFunction(()=>!__roamDiagnostics().auto,null,{timeout:110000}).catch(async e=>{console.error('Stalled route',JSON.stringify(await state(p)));throw e;});s=await state(p);assert.equal(s.region,destination===2?17:'luna'+({9:24,10:20,11:16}[destination]));assert.ok(s.environment.earthRendered);report.routes.push({region:s.region,seconds:Math.round((Date.now()-start)/1000)});console.log('Arrived '+s.region+' in '+report.routes.at(-1).seconds+' s');}
 // Existing branches must enter the Luna chain through the Blue Ghost approach.
 for(const i of [0,1,3,4,6,7,8]){await select(p,i,'jump');assert.equal((await state(p)).environment.earthRendered,i!==3&&i!==4);await select(p,11,'guide');s=await state(p);assert.ok(s.guidePath.some(a=>Math.hypot(a.x-(s.regions[5].x-12),a.z-(s.regions[5].z-15))<1));assert.ok(s.guidePath.some(a=>Math.hypot(a.x-(s.regions[10].x-12),a.z-(s.regions[10].z-15))<1));await p.keyboard.press('a');assert.equal((await state(p)).auto,false);}
 const phone=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});phone.on('pageerror',e=>report.errors.push(String(e)));await phone.goto(origin+'/roam.html');await phone.waitForFunction(()=>window.__roamDiagnostics?.().ready);
 for(const [i,width,height] of [[9,320,568],[10,390,844],[11,844,390]]){await phone.setViewportSize({width,height});await select(phone,i,'jump');await phone.waitForTimeout(300);const buttons=await phone.locator('#pad button').evaluateAll(bs=>bs.map(b=>{const r=b.getBoundingClientRect();return r.top>=0&&r.bottom<=visualViewport.height+.5&&r.left>=0&&r.right<=visualViewport.width+.5&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===b;}));assert.ok(buttons.every(Boolean));assert.equal(await phone.locator('#distance,#speed,#rate').count(),0);report.mobile.push({i,width,height,buttons});await phone.screenshot({path:path.join(output,'phone-'+width+'.png')});}
 assert.deepEqual(report.errors,[]);report.status='PASS';fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify(report,null,2));console.log('PASS Luna 24/20/16, three codex unlocks, descent/ascent split, complete driving loop, saves and mobile');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
