const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/win/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),output=path.join(root,'_tmp/compact');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(path.relative(root,f).startsWith('..')||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.html':'text/html'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});
const state=p=>p.evaluate(()=>__roamDiagnostics());
async function select(p,i,action){await p.locator('#mapBtn').click();await p.locator(`[data-region="${i}"]`).click();await p.locator(`[data-action="${action}"]`).click();await p.waitForTimeout(250);}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),report={errors:[],routes:[],mobile:[]};
try{
 const p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>report.errors.push(String(e)));p.on('response',r=>{if(r.status()>=400)report.errors.push(r.status()+' '+r.url());});
 await p.addInitScript(()=>{if(window.name.startsWith('compact-seed:')){localStorage.setItem('moonexplorer-connected-drive-v1',window.name.slice(13));window.name='';}window.mapTexts=[];const fill=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(t,...a){if(this.canvas.id==='routeMap')window.mapTexts.push(String(t));return fill.call(this,t,...a);};});
 await p.goto(origin+'/roam.html');await p.waitForFunction(()=>window.__roamDiagnostics?.().ready);assert.equal((await state(p)).codex.total,38);assert.equal(await p.locator('#distance,#speed,#rate').count(),0);
 const L=require('../roam-layout');
 // Previous saves keep the same position within each unchanged exhibit; version 2 reloads only once.
 for(let i=0;i<8;i++){
   await p.evaluate(({pos,id})=>window.name='compact-seed:'+JSON.stringify({version:1,x:pos.x-12,z:pos.z-15,yaw:.56,visited:[15,id],heritage:false,totalTravel:123}),{pos:L.legacy[i],id:[15,16,17,6,4,'bg1',3,5][i]});await p.reload();await p.waitForFunction(()=>window.__roamDiagnostics?.().ready);let s=await state(p);assert.ok(Math.hypot(s.position.x-(L.positions[i].x-12),s.position.z-(L.positions[i].z-15))<.001);assert.equal(s.heritage,false);assert.equal(s.environment.earthRendered,i<3||i>=5);assert.ok(s.visited.includes([15,16,17,6,4,'bg1',3,5][i]));
   await select(p,i,'jump');const before=(await state(p)).position;await p.reload();await p.waitForFunction(()=>window.__roamDiagnostics?.().ready);s=await state(p);assert.ok(Math.hypot(s.position.x-before.x,s.position.z-before.z)<.001);
 }
 const s=await state(p),offsets=[[-2,20],[-20,8],[-25,16],[0,4],[0,8],[0,4],[0,8],[0,4],[0,8],[0,4],[0,4],[0,4],[0,8],[0,8],[0,4],[0,4],[0,4],[0,4],[0,4],[0,4],[0,4],[0,4],[0,4],[0,4]];s.exhibits.forEach((e,i)=>{assert.ok(Math.abs(e.lander.x-s.regions[i].x-offsets[i][0])<1e-9);assert.ok(Math.abs(e.lander.z-s.regions[i].z-offsets[i][1])<1e-9);});
 await select(p,0,'jump');await p.locator('#mapBtn').click();const text=await p.locator('#atlas').innerText();assert.ok(!/压缩|游戏米|当前直线距离/.test(text));for(const value of ['776 km','1,121 km','995 km','3,896 km','632 km','888 km'])assert.ok(text.includes(value));await p.locator('[data-region="5"]').click();assert.ok((await p.locator('#mapSelection').innerText()).includes('1,635 km'));assert.ok(!(await p.evaluate(()=>mapTexts.join(' '))).match(/\b\d+ m\b/));await p.screenshot({path:path.join(output,'real-distance-map.png')});await p.locator('#closeMap').click();
 // Traverse every shortened road, including return legs for both newest destinations.
 for(const destination of [2,5,2,1,3,4,3,1,0]){
   await select(p,destination,'guide');const start=Date.now();assert.equal((await state(p)).auto,true);await p.waitForFunction(()=>!__roamDiagnostics().auto,null,{timeout:125000});const s=await state(p);assert.equal(s.region,[15,16,17,6,4,'bg1',3,5][destination]);assert.equal(s.environment.earthRendered,destination<3||destination===5);report.routes.push({region:s.region,seconds:Math.round((Date.now()-start)/1000),position:s.position});console.log('Arrived '+s.region+' in '+report.routes.at(-1).seconds+' s');
 }
 await select(p,5,'jump');await p.screenshot({path:path.join(output,'driving-without-distance.png')});
 const phone=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});phone.on('pageerror',e=>report.errors.push(String(e)));await phone.goto(origin+'/roam.html');await phone.waitForFunction(()=>window.__roamDiagnostics?.().ready);
 for(const [width,height] of [[320,568],[390,844],[844,390]]){await phone.setViewportSize({width,height});await phone.waitForTimeout(200);assert.equal(await phone.locator('#distance').count(),0);const buttons=await phone.locator('#pad button').evaluateAll(bs=>bs.map(b=>{const r=b.getBoundingClientRect();return r.top>=0&&r.bottom<=visualViewport.height+.5&&r.left>=0&&r.right<=visualViewport.width+.5&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===b;}));assert.ok(buttons.every(Boolean));report.mobile.push({width,height,buttons});await phone.screenshot({path:path.join(output,'phone-'+width+'.png')});await phone.locator('#mapBtn').click();await phone.locator('[data-region="5"]').click();assert.ok((await phone.locator('#mapSelection').innerText()).includes('1,635 km'));await phone.locator('#closeMap').click();}
 assert.deepEqual(report.errors,[]);report.status='PASS';fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify(report,null,2));console.log('PASS compact routes, intact exhibits, real distance UI, legacy saves, Earth visibility and mobile');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
